### ISSUE TITLE
兄弟 ,  你的xiaorui.cc 为什么无法评论了? 

### ISSUE THREAD

**Issue by ayanmw** [rfyiamcool/rfyiamcool#2]
你好:

# 你的博客站点评论异常问题
在你的博客站点, http://xiaorui.cc/archives/1158 ,我想评论一下

但当 我 点击评论按钮, 直接返回的是下载文件:
http://mirrors.163.com/centos/7/os/x86_64/images/boot.iso 

根据chrome Network的 Initiator 是 这个地址 直接返回的: "http://xiaorui.cc/wp-comments-post.php" 
所以 你的站点不是被黑了把?

## 本来想评论的内容 <关于爬虫抓取博客文章的>
你抱怨有人爬你的内容, 侵犯你的文章, 我想回复:
    对于没有节操的网站, 最好的办法就是 黑掉他 , 删数据库, 删文件系统 rm -rf / ; 
    无奈啊, 现在网上垃圾太多了, 网上冲浪, 早就变成了 网上冲垃圾海。
    不过看到 <风云就她了> 这样的站点, 还是很欣慰的.

    友情提示
之前貌似看到有一个博客用了 维权骑士 这个网站, 要不 你了解下?? ps:不是广告, 只是联想到了, 感觉还是有点意思和意义的.
https://rightknights.com/ 

## 好奇心
我是一个游戏公司的服务器主程, 用的是golang, 自己写的框架. MORPG游戏类型.
我一直感叹自己的能力不足,奈何 周围也没什么能力出众的. 
之前还写博客,自己也喜欢研究技术, 都是工作外的.
现在 公司都tmd 用内网开发, 不注重技术, 没有技能分享的地方, 好烦的.
很羡慕你现在的状态, 以及你公司的这种氛围.
不知道 你们公司是那家公司? 以及你的简介 也没有? (github xiaorui)

**Comment by ayanmw** [comment]
@rfyiamcool  给你的 rfyiamcool#163.com  发邮件 , 也没回复, 不知道是什么问题.
这里 at 一下你,  算了.

**Comment by rfyiamcool** [comment]
那是很久以前的事情了，不好意思。以前随便写的按照规则防抓取，年久失修早就出问题了，也没去管。😅
